backend:
  name: git-gateway
  branch: master
  repo: github.com/iaeiou/wonderful-cms-on-netlify

media_folder: "static/images"
public_folder: "/images"

locale: 'fr'

publish_mode: editorial_workflow

localbackend: true

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "-"
    fields:
      - {label: "Draft", name: draft, widget: "hidden", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
