backend:
  name: git-gateway
  branch: main
  repo: https://github.com/iaeiou/WonderfulHugo-netlify-CMS

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Draft", name: draft, widget: "boolean", default: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Series", name: series, widget: "list"}
      - {label: "No Comment", name: "nocomment", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
